spring.application.name=techcup-futbol
server.port=8081
spring.data.mongodb.uri=mongodb://localhost:27017/lab8images
# Base logging (shared by all environments)
logging.file.name=logs/techcup-futbol.log
logging.level.root=INFO
logging.level.edu.eci.dosw.techcup_futbol=INFO
